a.out: hash_table.c
	gcc -o a.out -g -Wall hash_table.c 

#main: myprog
#
#C_COMPILER     = gcc
#C_OPTIONS      = -Wall -pedantic -g
#C_LINK_OPTIONS = -lm 
#CUNIT_LINK     = -lcunit
#
#%.o:  %.c
#	$(C_COMPILER) $(C_OPTIONS) $^ -c
#
#myprog: hash_table_tests.o hash_table.o
#	$(C_COMPILER) $(C_LINK_OPTIONS) $^ -o $@
#
##myprog.final: file1.o file2.o file3.o
## TODO: add e.g. optimisation flags, remove unnecessary linking, etc.
#
#clean:
#	rm -f *.o myprog